### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by zer0k-z** [KZGlobalTeam/cs2kz-metamod#100]

**Comment by zer0k-z** [comment]
Apparently valve nuked the only way for the server to get the client language, `cl_language` is not a userinfo cvar anymore.

**Comment by himenekocn** [comment]
I think we can first specify the server's default language, just like cssharp use !lang to change client language.

**Comment by zer0k-z** [comment]
https://github.com/komashchenko/ClientCvarValue/
