### ISSUE TITLE
Ramp bug fix prediction error

### ISSUE THREAD

**Issue by zer0k-z** [KZGlobalTeam/cs2kz-metamod#106]
And have a new bug, ramp bug fix or edge bug fix cause this i think

https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/39359822-ff6c-49a8-82da-edea6e6d72ae

_Originally posted by @himenekocn in https://github.com/KZGlobalTeam/cs2kz-metamod/issues/99#issuecomment-1927036390_

**Comment by zer0k-z** [comment]
Can't seem to replicate this.

**Comment by himenekocn** [comment]
> Can't seem to replicate this.

he send me wrong mapname , kz_sxb2_cxz is true
