### ISSUE TITLE
Does ramp bug fix will be a single plugin in the future? those people in cs2 surf need it

### ISSUE THREAD

**Issue by LaplaceTor** [KZGlobalTeam/cs2kz-metamod#111]
They ask me to thank you if you can do it

**Comment by zer0k-z** [comment]
I believe someone else already started porting it to the surf plugins. Also right now it's not fully functional because valve somehow broke it.

**Comment by LaplaceTor** [comment]
> I believe someone else already started porting it to the surf plugins. Also right now it's not fully functional because valve somehow broke it.

Actually the cs2 update few days ago is broken and ramp bug happen much much often than before, i see ws-cs2 is going to do but more and more people cannot waiting for it due to the fvking update

**Comment by zer0k-z** [comment]
The rampbug fix is broken on the kz plugin since that update as well.

**Comment by alnoisegit** [comment]
Now that it's fixed again, any chance we can get the fix in a standalone plugin? Will said he had no plans on adding it to CS2Fixes any time soon.

**Comment by zer0k-z** [comment]
It's unlikely for me to port it any time soon, given that it is not trivial to port it (it would have to include the underlying stuff like schema, tracing, hooks, etc..) and there are a lot of other higher priority issues to be addressed. Unless someone else is doing it, it's unlikely to happen before cs2kz gets officially released.
