### ISSUE TITLE
Allow noclipping by holding a key

### ISSUE THREAD

**Issue by AlphaKeks** [KZGlobalTeam/cs2kz-metamod#117]
Currently you can noclip with `kz_noclip`, which is a toggle. GOKZ had `+nc` and `+ncnt` which allowed you to hold down a key, which I prefer.

**Comment by AlphaKeks** [comment]
> Where did you find out about this command?

Which command? The GOKZ ones or `kz_noclip`?
I'm not sure where the GOKZ commands are documented outside the actual source code, but cs2kz has a `kz_help` command which should list all available commands. Besides that I'm just involved in the development and testing, so I know about it because of that.

Please keep in mind this plugin is still a WIP and not meant to be used by a lot of people. It changes very frequently, isn't documented properly, and will likely change quite a lot in the near future.

**Comment by zer0k-z** [comment]
+/- commands are not networked anymore so this is not possible.
