### ISSUE TITLE
strafe data error? 

### ISSUE THREAD

**Issue by LaplaceTor** [KZGlobalTeam/cs2kz-metamod#121]
![image](https://github.com/KZGlobalTeam/cs2kz-metamod/assets/28674126/62996bf9-2b7e-47b2-896a-1411fa9b5b1f)

**Comment by LaplaceTor** [comment]
Alright, strafe is broken now, no only the data

**Comment by zer0k-z** [comment]
do you have a clip of it happening?

**Comment by LaplaceTor** [comment]
> do you have a clip of it happening?

trigger broken is fix so it's a recent version, i got weird when i try to strafe in LJ room, and found it broken
