### ISSUE TITLE
!ssp doesnt work

### ISSUE THREAD

**Issue by tatuaua** [KZGlobalTeam/cs2kz-metamod#123]
If you set ssp inside timer zone and do !r it works, but not after exiting timer zone. If you set ssp outside timerzone and do !r it works, but not after entering timer zone. I assume that starting / stopping the timer clears all checkpoints including startpos.

**Comment by zer0k-z** [comment]
Fixed with https://github.com/KZGlobalTeam/cs2kz-metamod/commit/c25367ad79e6886743a0cb48024888b2300880c5
