### ISSUE TITLE
Add player can choose their preferred secondary weapon.

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#124]

**Comment by himenekocn** [comment]
@zer0k-z maybe need GiveNamedItem support?
https://github.com/himenekocn/cs2kz-metamod/tree/select-weapon
I fork a new branch, but my cpp is bad😰

**Comment by zer0k-z** [comment]
I think it's better to use CS2Fixes's https://github.com/Source2ZE/CS2Fixes/pull/121/ and strip it for pistol only.

**Comment by himenekocn** [comment]
CS# plugins for only pistol gun menu 
https://github.com/himenekocn/cs2-simple-guns-menu
