### ISSUE TITLE
Timer does not invalidate upon noclipping with sv_cheats on

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#126]
Some map force sv_cheats true on mapstart.
DetectNoclip did not call detection.

**Comment by himenekocn** [comment]
Maybe need force sv_cheats false?
Player can give weapon_awp or other weapons.

**Comment by zer0k-z** [comment]
Latest commit should fix it, lmk if it doesn't

**Comment by himenekocn** [comment]
> Latest commit should fix it, lmk if it doesn't
![QQ截图20240219030833](https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/f72d5543-3b99-4d96-ad36-513b56a1433f)

Timer still running.

**Comment by zer0k-z** [comment]
Ah, when you said DetectNoclip I thought it was the jumpstats service's `DetectNoclip` function.

**Comment by himenekocn** [comment]
> Ah, when you said DetectNoclip I thought it was the jumpstats service's `DetectNoclip` function. Timer has no protection against noclip, it's planned for rework later.

And `+noclip -noclip +nc -nc` doesn't seem to work, or maybe I don't know the correct usage?

**Comment by zer0k-z** [comment]
yeah doesn't work. +/- commands aren't networked anymore.
