### ISSUE TITLE
Crash on new dev version

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#130]
when more player join server, server will crash.

**Comment by himenekocn** [comment]
still crash @zer0k-z

**Comment by zer0k-z** [comment]
Could you send the accelerator crash dump as well?

**Comment by himenekocn** [comment]
> Could you send the accelerator crash dump as well?



> Could you send the accelerator crash dump as well?

It seems to be in conflict with CS#. If I remove CS#, it won't crash

**Comment by himenekocn** [comment]
opss, it crash

**Comment by himenekocn** [comment]
[5dee60cc-c4d4-4d2b-051da186-a96842e4.dmp.txt](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14420508/5dee60cc-c4d
[cs2kz.zip](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14420511/cs2kz.zip)
4-4d2b-051da186-a96842e4.dmp.txt)

**Comment by himenekocn** [comment]
[5dee60cc-c4d4-4d2b-051da186-a96842e4.dmp.txt](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14420512/5dee60cc-c4d4-4d2b-051da186-a96842e4.dmp.txt)
[cs2kz.zip](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14420513/cs2kz.zip)
@zer0k-z
