### ISSUE TITLE
Question about the configuration

### ISSUE THREAD

**Issue by Mr-Robot-ops** [KZGlobalTeam/cs2kz-metamod#165]
Is it possible in a config to turn off the panel and stats for all players by default? And how can I activate Auto Bhop?

**Comment by zer0k-z** [comment]
> Is it possible in a config to turn off the panel and stats for all players by default?

No, not yet.

> And how can I activate Auto Bhop?

`!style autobhop` or `/style autobhop` in chat or `kz_style autobhop` in console.
