### ISSUE TITLE
Make prestrafing a feature if possible 

### ISSUE THREAD

**Issue by sjhaleprogrammer** [KZGlobalTeam/cs2kz-metamod#17]
top priority feature other then timer and menu

**Comment by zer0k-z** [comment]
Menu is not possible right now, valve nuked it off CS2.

**Comment by sjhaleprogrammer** [comment]
what about prestrafing fuk the menu

**Comment by zer0k-z** [comment]
that's gonna be on hold until https://github.com/alliedmodders/metamod-source/pull/135 is done.

**Comment by sjhaleprogrammer** [comment]
Ggwp lol

**Comment by zer0k-z** [comment]
Prestrafe's now part of CKZ.
