### ISSUE TITLE
Spectators can't chat with players

### ISSUE THREAD

**Issue by busheezy** [KZGlobalTeam/cs2kz-metamod#21]
This isn't specific to CS2KZ but it impacts us a bit heavy. Currently, spectators can not talk to players on a team. A chat processor is inevitable and this should be a quick start.

**Comment by zer0k-z** [comment]
Hm, sv_full_alltalk 1 and sv_talk_enemy_dead 1 in the cfg file wasn't enough?

**Comment by zer0k-z** [comment]
Might be fixed with the latest update on master now, seems to be a problem with the game rules constructor.

**Comment by busheezy** [comment]
We've discussed this a bit on discord. @zer0k-z has realized that  realized sv_full_alltalk is reset for warmup, halftime, and match ending. This happened on CSGO as well.

https://github.com/KZGlobalTeam/gokz/blob/master/addons/sourcemod/scripting/gokz-core/misc.sp#L231

**Comment by zer0k-z** [comment]
Resolved here https://github.com/KZGlobalTeam/cs2kz-metamod/commit/99d587125c18c92c11eff1c7b782e4c1c496bc38#diff-2dc3ed7917a3f5303aad049431ea3f473b8893b5a5ab977ee209a4c29b06c15dR254
