### ISSUE TITLE
mysql windows server issus

### ISSUE THREAD

**Issue by e54385991** [KZGlobalTeam/cs2kz-metamod#248]
I am encountering the following error on my Windows server: 
`Failed to establish a MySQL connection: SSL connection error: Unable to get certificate [KZDB] Failed to connect. Destroying MySQL connection cs2kz. Using spawn points configuration 0x009F8197.' `

However, the connection works fine on my Linux server, even though both servers are using the same database. Can anyone help me understand why this discrepancy occurs?

**Comment by zer0k-z** [comment]
I'm not sure, maybe your database server is using SSL, and the windows game server doesn't have the root certificates required unlike the linux servers?

**Comment by e54385991** [comment]
> I'm not sure, maybe your database server is using SSL, and the windows game server doesn't have the root certificates required unlike the linux servers?

I have a fresh installation of Windows Server 2022, but the issue persists. I really don't know how to resolve it.

**Comment by zer0k-z** [comment]
Try disable SSL in your mysql server.

**Comment by e54385991** [comment]
[mysqld]
skip_ssl 
it's workfine.
