### ISSUE TITLE
cs2大行动更新后，cs2kz无法使用

### ISSUE THREAD

**Issue by zyhsck** [KZGlobalTeam/cs2kz-metamod#250]
metamod我使用的是最新的1314，metamod能加载，但是在加载cs2kz是报错，显示:[META] Failed to load plugin addons\cs2kz\bin\win64\cs2kz: 找不到指定的程序。
[META] Loaded 0 plugins.

**Comment by zer0k-z** [comment]
I don't know what you mean by this but the plugin is not fixed yet.
