### ISSUE TITLE
some map server crash?

### ISSUE THREAD

**Issue by e54385991** [KZGlobalTeam/cs2kz-metamod#263]
# Map:kz_isuper
# OS: Linux Debian 12.7

console output: 
Created physics for kz_isuper
cs2: /app/src/kz/mappingapi/kz_mappingapi.cpp:455: void Mapi_OnInfoTeleportDestinationSpawn(const EntitySpawnInfo_t *): Assertion `0' failed.
The server crashed immediately.

**Comment by zer0k-z** [comment]
The mapper uses the mapping API with info_teleport_destination entity named `timer_start` but they didn't specify the course descriptor for it.
