### ISSUE TITLE
Teams are limited to 8

### ISSUE THREAD

**Issue by busheezy** [KZGlobalTeam/cs2kz-metamod#33]
It seems once a team has 8 players, nobody else can join it. I tested this on a 64 slot server. Players will get something along the lines of "Team Full" and be stuck in the team select screen or spectator. I would love for someone to prove this incorrect. I am currently limiting all of my servers to 16 slots to prevent any issues.

I've tried:
```
mp_autoteambalance 0
mp_limitteams 0 and mp_limitteams 32
```

**Comment by LaplaceTor** [comment]
This is probably because of convar settings in map's vpk , ask mapper for help ( A new update in 12/14 add MD5 check of the map so perhaps it's not impossible to edit vpk ever...

**Comment by zer0k-z** [comment]
If it was a simple convar change then the plugin should be able to easily change it, but I haven't found a convar that lets me override this behavior.

**Comment by LaplaceTor** [comment]
> If it was a simple convar change then the plugin should be able to easily change it, but I haven't found a convar that lets me override this behavior.

Yeah right, I 've got a lot of game report in my server that some maps limit to 1 /2 /5 /8 human per teams, but convar changing is not working

**Comment by LaplaceTor** [comment]
I found this in a workshop comment, fix it well

> Hi, can you add more info_player_(counter)terrorist. Because only 2 player perteam can play.
> with sv_cheats true & ent_find info_player_counterterrorist I found only 2 matches

So if you want more than 8 players per team , you should ask author to add more 
I think 10 players per team is a better settings

**Comment by zer0k-z** [comment]
It is a problem with number of spawns. It should fixes itself by making 64 spawn points for each team but ideally this should be handled plugin side.

**Comment by zer0k-z** [comment]
Should be fixed with #96.
