### ISSUE TITLE
How to instal plugin into dathost server

### ISSUE THREAD

**Issue by donjells** [KZGlobalTeam/cs2kz-metamod#53]
Hello! 

Can I get some help to set up a KZ server with dathost? Ive tried asking for help there but they told me to come and ask the developers for help. 

Ive tried downloading v0.0.1 linux and windows versions and tried to instal these onto the addons folder without any luck.

What could I be doing wrong?

Thanks in advance

**Comment by LaplaceTor** [comment]
Ask there for which system they're, and don't place both system's file in, just the right one is OK, but both in would failed to load
And linux plugin is now unusable, so if you're linux you should wait until fix it
Last thing is, some features are base on cs2fixes so you need to install cs2fixes to run it, which is not compatible with cssharp, that a lot new plugins is base on cssharp so you cannot use them

**Comment by GameChaos** [comment]
you don't need to isntall cs2fixes to run this plugin

**Comment by donjells** [comment]
I just read from tech support in Dat Host that they use Linux and that currently the Linux Version of the KZ plugin doesn't work. Is this true? I just want a teleport feature in my server, also can't get to load the "only up" map. Everything seems so unnecesarily hard.

**Comment by zer0k-z** [comment]
The linux version is currently broken, the fix is on the way... slowly

**Comment by zer0k-z** [comment]
Plugin on dev branch should work now on linux.
