### ISSUE TITLE
not work, need update offsets

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#55]
use dev version

**Comment by himenekocn** [comment]
"Teleport"
           {
                "windows"   "149"
                "linux"     "148"
            }
	   "IsEntityPawn"
            {
                "windows"   "153"
                "linux"     "152"
            }
	   "IsEntityController"
            {
                "windows"   "154"
                "linux"     "153"
            }

**Comment by himenekocn** [comment]
"CollisionRulesChanged"
            {
                "windows"   "174"
                "linux"     "173"
            }

**Comment by GameChaos** [comment]
duplicate of #54
