### ISSUE TITLE
The same as cs2fixes, cs2kz is not compatible with cssharp

### ISSUE THREAD

**Issue by LaplaceTor** [KZGlobalTeam/cs2kz-metamod#56]
you don't need to isntall cs2fixes to run this plugin

_Originally posted by @GameChaos in https://github.com/KZGlobalTeam/cs2kz-metamod/issues/53#issuecomment-1852781958_
            
So I think I should use cs2fixes for more features at this moment ....

**Comment by zer0k-z** [comment]
Both CS2Fixes and CS# plugins are not compatible with the metamod plugin because they all detour the same function, but only  one of them will work.

**Comment by LaplaceTor** [comment]
> Both CS2Fixes and CS# plugins are not compatible with the metamod plugin because they all detour the same function, but only one of them will actually be able to hook the function and work properly.

They're Ok in windows server but not in linux, at this time I've got 3 windows kz server with desubtick and movement unlocker
Anyway ,  I'm excited to wait for your working on movement, with desubtick and movement unlocker build-in

**Comment by zer0k-z** [comment]
Movement unlocker will unlikely be in KZ because it fundamentally gives autobhop (that's why CS:S bhop was so "easy")

External desubtick plugins will break in the future once KZ plugin starts hooking onto the same function, it's just not the case for the dev branch yet.

**Comment by zer0k-z** [comment]
Dev version should be compatible with CS# now.
