### ISSUE TITLE
Server Crash when player join spectators

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#65]
Server Crash when player join spectators team

**Comment by himenekocn** [comment]
and sometimes will crash on Windows when player finish the map

**Comment by zer0k-z** [comment]
Which version of the plugin are you using? latest dev release

**Comment by himenekocn** [comment]
dev

**Comment by himenekocn** [comment]
> Which version of the plugin are you using? latest dev release?

 latest mode release

**Comment by himenekocn** [comment]
> Which version of the plugin are you using? latest dev release?

I test on linux & windows server
the crash is happen on when players change they mode to CKZ, and join to spectators, server will crash 100%

**Comment by zer0k-z** [comment]
Could you take a look at the latest commit on `mode` branch and see if it fixed the crash?

**Comment by himenekocn** [comment]
> Could you take a look at the latest commit on `mode` branch and see if it fixed the crash?

this is fixed
but, now it will crash when map change..

**Comment by zer0k-z** [comment]
Just pushed another update for this, it is still crashing?

**Comment by himenekocn** [comment]
> Just pushed another update for this, it is still crashing?

In my testing, join spectator and mapchange no crash, but still random crash, sometime is finish map.

**Comment by himenekocn** [comment]
> Just pushed another update for this, it is still crashing?

find the reason, when player checkpoint on ladder, and tp to checkpoint will crash server

**Comment by LaplaceTor** [comment]
Windows would crash after someone finish map 
Ladder teleport would crash server , not checkpoint

**Comment by zer0k-z** [comment]
can you verify this still happens with the latest dev version?

**Comment by himenekocn** [comment]
> can you verify this still happens with the latest dev version?

cant jump on linux

**Comment by zer0k-z** [comment]
hm, i can't seem to replicate that on linux

**Comment by himenekocn** [comment]
> hm, i can't seem to replicate that on linux, do you have a clip of that happening?

no problem now, my server break

**Comment by himenekocn** [comment]
> hm, i can't seem to replicate that on linux, do you have a clip of that happening?

Found chain offset 8 for CCSPlayer_MovementServices::m_bOldJumpPressed

**Comment by zer0k-z** [comment]
> > hm, i can't seem to replicate that on linux, do you have a clip of that happening?
> 
> Found chain offset 8 for CCSPlayer_MovementServices::m_bOldJumpPressed

that should be normal output with dev/debug launch options, this doesn't mean much
