### ISSUE TITLE
Some map portal triggers have failed

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#99]
Some map portal triggers have failed 
dev new version

**Comment by himenekocn** [comment]
need fix!

**Comment by himenekocn** [comment]
and sometimes server will crash when more player

**Comment by zer0k-z** [comment]
what map were you running, do you have a clip of it happening, and is there any crash log?

**Comment by himenekocn** [comment]
All map with Portal cannot enter that

**Comment by himenekocn** [comment]
[1eba49aa-5c02-47a7-e5614f80-1adc4d99.dmp.txt](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14152220/1eba49aa-5c02-47a7-e5614f80-1adc4d99.dmp.txt)

**Comment by zer0k-z** [comment]
just to be sure, it crashed on [321f898](https://github.com/KZGlobalTeam/cs2kz-metamod/releases/tag/dev-321f898) right?

**Comment by himenekocn** [comment]
> just to be sure, it crashed on [321f898](https://github.com/KZGlobalTeam/cs2kz-metamod/releases/tag/dev-321f898) right?

no, I forked a compilation on the server, but the only change was to translate it from English to Chinese.

Even the dev version of the portal cannot be used.

**Comment by himenekocn** [comment]
> just to be sure, it crashed on [321f898](https://github.com/KZGlobalTeam/cs2kz-metamod/releases/tag/dev-321f898) right?

Version before Triggerfix is work good

**Comment by zer0k-z** [comment]
can you send the cs2kz.so that you compiled then? the log isn't very useful without having access to the binary itself.

**Comment by himenekocn** [comment]
[cs2kz.zip](https://github.com/KZGlobalTeam/cs2kz-metamod/files/14152242/cs2kz.zip)


> can you send the cs2kz.so that you compiled then? the log isn't very useful without having access to the binary itself.

**Comment by zer0k-z** [comment]
Pushed https://github.com/KZGlobalTeam/cs2kz-metamod/commit/e585ebc5b76359f9761c68187a0c596f8fd4fa19 attempting to fix the crash, let me know if it works. For the issue where the trigger doesn't work, I tried kz_igneous and kz_grotto on server with 1 person and I couldn't replicate it.

**Comment by himenekocn** [comment]
> Pushed [e585ebc](https://github.com/KZGlobalTeam/cs2kz-metamod/commit/e585ebc5b76359f9761c68187a0c596f8fd4fa19) attempting to fix the crash, let me know if it works. For the issue where the trigger doesn't work, I tried kz_igneous and kz_grotto on server with 1 person and I couldn't replicate it.

try kz_sxb2_cxz
spawnpoint have a portal

**Comment by himenekocn** [comment]
> Pushed [e585ebc](https://github.com/KZGlobalTeam/cs2kz-metamod/commit/e585ebc5b76359f9761c68187a0c596f8fd4fa19) attempting to fix the crash, let me know if it works. For the issue where the trigger doesn't work, I tried kz_igneous and kz_grotto on server with 1 person and I couldn't replicate it.

oh, trigger fix on new version now , thx

**Comment by himenekocn** [comment]
@zer0k-z It still have trigger problem.

**Comment by himenekocn** [comment]
After testing with players on my server, there is a chance that the portal can be accessed, but often it cannot be accessed

**Comment by himenekocn** [comment]
https://pan.himeneko.cn/s/8nLtR

this is the record video, some players can access

**Comment by himenekocn** [comment]
And have a new bug, ramp bug fix or edge bug fix cause this i think

https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/39359822-ff6c-49a8-82da-edea6e6d72ae

**Comment by zer0k-z** [comment]
> And have a new bug, ramp bug fix or edge bug fix cause this i think
> 
> https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/39359822-ff6c-49a8-82da-edea6e6d72ae
> 
> 

which map is this?

**Comment by himenekocn** [comment]
> > And have a new bug, ramp bug fix or edge bug fix cause this i think
> > 
> >   
> >     
> >     
> > 
> >     2024-02-05.21-34-44.mp4
> 
> which map is this?

i think is not map problem, it seems to be the second player who will do this after entering the server

**Comment by himenekocn** [comment]
> > And have a new bug, ramp bug fix or edge bug fix cause this i think
> > 
> >   
> >     
> >     
> > 
> >     2024-02-05.21-34-44.mp4
> 
> which map is this?

kz_kiwi_hym

**Comment by himenekocn** [comment]
https://github.com/KZGlobalTeam/cs2kz-metamod/assets/9393126/f156de67-b2cb-4e0d-93f0-c0164b831f61

@zer0k-z you can watch this video, Trigger it seems to only take effect on the first and second people who enter the server, Players who enter later cannot trigger it

**Comment by zer0k-z** [comment]
Should be fixed in the latest dev commit, reopen this if the issue persists.
